repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
  - repo: local
    hooks:
      - id: golangci-lint
        name: go linter
        pass_filenames: false
        types: [ go ]
        entry: golangci-lint run
        language: system
      - id: go-unit-tests
        name: go unit tests
        entry: env STRIPE_MOCK_ENABLED=false go test ./... -coverprofile=coverage.out -coverpkg=everbit-software/docs-maker-api/internal/repository,everbit-software/docs-maker-api/internal/service,everbit-software/docs-maker-api/internal/utils,everbit-software/docs-maker-api/internal/database,everbit-software/docs-maker-api/internal/model,everbit-software/docs-maker-api/internal/middleware
        pass_filenames: false
        types: [ go ]
        language: system
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]
