// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClipsColumns holds the columns for the "clips" table.
	ClipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString},
		{Name: "audio_path", Type: field.TypeString},
		{Name: "video_path", Type: field.TypeString},
		{Name: "gen_captions_path", Type: field.TypeString, Nullable: true},
		{Name: "gen_raw_video_path", Type: field.TypeString, Nullable: true},
		{Name: "gen_trimmed_video_path", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// ClipsTable holds the schema information for the "clips" table.
	ClipsTable = &schema.Table{
		Name:       "clips",
		Columns:    ClipsColumns,
		PrimaryKey: []*schema.Column{ClipsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClipsTable,
	}
)

func init() {
}
