// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sam-laister/tiktok-creator/ent/clip"
	"github.com/sam-laister/tiktok-creator/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	clipFields := schema.Clip{}.Fields()
	_ = clipFields
	// clipDescCreatedAt is the schema descriptor for created_at field.
	clipDescCreatedAt := clipFields[6].Descriptor()
	// clip.DefaultCreatedAt holds the default value on creation for the created_at field.
	clip.DefaultCreatedAt = clipDescCreatedAt.Default.(func() time.Time)
	// clipDescUpdatedAt is the schema descriptor for updated_at field.
	clipDescUpdatedAt := clipFields[7].Descriptor()
	// clip.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	clip.DefaultUpdatedAt = clipDescUpdatedAt.Default.(func() time.Time)
}
